# Generated by Django 4.1.2 on 2023-01-20 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='contact',
            field=models.CharField(default='contact', max_length=15),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='designation',
            field=models.CharField(default='Designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='empdept',
            field=models.CharField(default='Department', max_length=100),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, null=True)),
                ('Num_day', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
